### ISSUE TITLE
Finalize Message format and adjust implementation

### ISSUE THREAD

**Issue by ckoopmann** [ultrasoundmoney/oracle-client#3]
Currently the messages have the following format:
`PriceMessage = { value: u64 }` with the price being represented as a fixed point number with 6 decimals of precision.

This is likely not the final format we want so we should decide on a message format including:

1. *Additional fields* that we want to add (timestamp, slot number, validator public key) 
2. *Additional types of messages* ("price is within x% of certain value", "price is above certain value")
3. *Granularity of price data*(especially if we want to efficiently bls-aggregate some of the messages mentioned in 2. we need a sufficiently coarse granualrity to ensure we have many messages with identical content)
4. *Signature scheme*: What parts of each message are going to be signed (timestamp?, slot number ? ). Are certain parts of the messages going to be signed individually or everything together ?

**Comment by JustinDrake** [comment]
> with the price being represented as a fixed point number with 6 decimals of precision

**Comment by JustinDrake** [comment]
> the price being represented as a fixed point number with 6 decimals of precision

Intuitively 2 decimals for USD feels sufficient. If the USD hyperinflates (and ETH succeeds), having a bit more space for very large numbers may make sense.

> Additional fields that we want to add (timestamp, slot number, validator public key)

Adding both the timestamp and slot number makes sense to me. One reason is that slot lengths may change in the future, changing the mapping from slot numbers to timestamps. The validator index or pubkey should be included in a "wrapper" object, along with the signature.

> Signature scheme: What parts of each message are going to be signed (timestamp?, slot number ? ). Are certain parts of the messages going to be signed individually or everything together ?

Signing over the timestamp and slot number makes sense to me!
